rh/urls.py
from django.urls import path
from .views import list_funcionarios, list_salarios, list_beneficios, form_funcionarios

urlpatterns = [
    path('funcionarios/', list_funcionarios, name="list_funcionarios"),
    path('salarios/', list_salarios, name="list_salarios"),
    path('beneficios/', list_beneficios, name="list_beneficios"),
    path('cadastrar_funcionario/', form_funcionarios, name="form_funcionarios"),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('rh.urls')),
    path('', include('ti.urls')),
    path('', include('financeiro.urls')),
]

ti/urls.py
from django.urls import path
from .views import relatorio_chips, planilha_pass_ip, inativar_email, planilha_emails, form_addti, banir_numero, reciclar_numero, reciclado_numero, excluir_numb, excluir_email

urlpatterns = [
    path('form_addti/', form_addti, name="form_addti"),
    path('relatorio_chips/', relatorio_chips, name="relatorio_chips"),
    path('planilha_pass_ip/', planilha_pass_ip, name="planilha_pass_ip"),
    path('planilha_emails/', planilha_emails, name="planilha_emails"),
    path('banir_numero/<str:numero>/<str:date_hour>/', banir_numero, name='banir_numero'),
    path('reciclar_numero/<str:numero>/<str:date_hour>/', reciclar_numero, name='reciclar_numero'),
    path('reciclado_numero/<str:numero>/<str:date_hour>/', reciclado_numero, name='reciclado_numero'),
    path('excluir_numb/<str:numero>/<str:date_hour>/', excluir_numb, name='excluir_numb'),
    path('inativar_email/<str:email>/<str:date_hour>/', inativar_email, name='inativar_email'),
    path('excluir_email/<str:email>/<str:date_hour>/', excluir_email, name='excluir_email'),
]

ti/models.py
from django.db import models

class NumbEmail(models.Model):
    cpf = models.CharField(max_length=11)
    email = models.EmailField(blank=True, null=True)
    senha_email = models.CharField(max_length=100, blank=True, null=True)
    operadora_site = models.CharField(max_length=11, blank=True, null=True, default="desconhecido")
    ddd = models.CharField(max_length=2, blank=True, null=True, default="00")
    numero = models.CharField(max_length=9, blank=True, null=True)
    status_numb = models.CharField(max_length=12, blank=True, null=True, default="ativo")
    status_email = models.CharField(max_length=12, blank=True, null=True, default="ativo")
    data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"CPF: {self.cpf}, Email: {self.email}, Operadora/Site: {self.operadora_site}, DDD: {self.ddd}, Número: {self.numero}"

ti/forms.py
from django import forms
from .models import NumbEmail

class NumbEmailForm(forms.ModelForm):
    class Meta:
        model = NumbEmail
        fields = '__all__'

ti/views.py
from django.shortcuts import render, redirect
from .forms import NumbEmailForm
from rh.models import Funcionario
from .models import NumbEmail
from datetime import datetime
import re
from django.db.models import DateField
from dateutil.parser import parse
from django.http import QueryDict



def sucesso(request):
    return render(request, 'apps/ti/planilha_emails.html')

from django.db.models import DateField

def banir_numero(request, numero, date_hour):
    # Fazer o parse da string da data e hora para um objeto datetime
    datetime_object = parse(date_hour)

    # Encontrar os objetos NumbEmail com base no número e data/hora e atualizar o status de todos os números para "banido"
    NumbEmail.objects.filter(numero=numero, data=datetime_object).update(status_numb='banido')
    
    # Redirecionar de volta para a URL atual
    return redirect(request.META.get('HTTP_REFERER', 'relatorio_chips'))

def reciclar_numero(request, numero, date_hour):
    # Fazer o parse da string da data e hora para um objeto datetime
    datetime_object = parse(date_hour)

    # Encontrar os objetos NumbEmail com base no número e data/hora e atualizar o status de todos os números para "reciclar"
    NumbEmail.objects.filter(numero=numero, data=datetime_object).update(status_numb='reciclar')
    
    # Redirecionar de volta para a URL atual
    return redirect(request.META.get('HTTP_REFERER', 'relatorio_chips'))

def reciclado_numero(request, numero, date_hour):
    # Fazer o parse da string da data e hora para um objeto datetime
    datetime_object = parse(date_hour)

    # Encontrar os objetos NumbEmail com base no número e data/hora e atualizar o status de todos os números para "reciclado"
    NumbEmail.objects.filter(numero=numero, data=datetime_object).update(status_numb='reciclado')
    
    # Redirecionar de volta para a URL atual
    return redirect(request.META.get('HTTP_REFERER', 'relatorio_chips'))

def excluir_numb(request, numero, date_hour):
    # Fazer o parse da string da data e hora para um objeto datetime
    datetime_object = parse(date_hour)

    # Encontrar e excluir_numb o objeto NumbEmail com base no número e data/hora
    NumbEmail.objects.filter(numero=numero, data=datetime_object).delete()
    
    # Redirecionar de volta para a URL de referência na solicitação
    return redirect(request.META.get('HTTP_REFERER', 'relatorio_chips'))

def excluir_email(request, email, date_hour):
    # Fazer o parse da string da data e hora para um objeto datetime
    datetime_object = parse(date_hour)

    # Encontrar e excluir_email o objeto NumbEmail com base no número e data/hora
    NumbEmail.objects.filter(email=email, data=datetime_object).delete()
    
    # Redirecionar de volta para a URL de referência na solicitação
    return redirect(request.META.get('HTTP_REFERER', 'relatorio_chips'))

def inativar_email(request, email, date_hour):
    # Fazer o parse da string da data e hora para um objeto datetime
    datetime_object = parse(date_hour)

    # Encontrar os objetos NumbEmail com base no número e data/hora e atualizar o status de todos os números para "reciclado"
    NumbEmail.objects.filter(email=email, data=datetime_object).update(status_email='inativo')
    
    # Redirecionar de volta para a URL atual
    return redirect(request.META.get('HTTP_REFERER', 'relatorio_chips'))

def planilha_pass_ip(request):
    return render(request, 'apps/ti/planilha_pass_ip.html')

def planilha_emails(request):
    # Inicialize listas vazias para armazenar os dados que serão exibidos na tabela
    dados_relatorio = []

    # Recupere todos os objetos NumbEmail do banco de dados
    num_emails = NumbEmail.objects.all()
    if request.method == 'GET':
        data_inicio = request.GET.get('data_inicio')
        data_fim = request.GET.get('data_fim')

        if data_inicio and data_fim:
            # Converta as datas de string para objetos datetime
            data_inicio = datetime.strptime(data_inicio, '%Y-%m-%d')
            data_fim = datetime.strptime(data_fim, '%Y-%m-%d')

            num_emails = NumbEmail.objects.filter(data__range=(data_inicio, data_fim))

            # Itere sobre os objetos NumbEmail para processar os dados
            for num_email in num_emails:
                # Inicialize as variáveis gerais como vazias
                cpf = ""
                nome_completo = ""
                setor = ""
                email = ""
                status = ""
                date_hour = ""

                # Verifique se há um email associado (não vazio)
                if num_email.email:
                    # Recupere o funcionário associado ao CPF do objeto NumbEmail
                    try:
                        funcionario = Funcionario.objects.get(cpf=num_email.cpf)
                    except Funcionario.DoesNotExist:
                        funcionario = None

                    # Verifique se o funcionário foi encontrado e está ativo
                    if funcionario and funcionario.status_atividade == 'ativo':
                        # Preencha as variáveis com os dados do funcionário e do objeto NumbEmail
                        cpf = num_email.cpf
                        nome_completo = funcionario.nome_completo
                        setor = funcionario.setor
                        email = num_email.email
                        status = num_email.status_email
                        date_hour = num_email.data

                        # Adicione os dados à lista de dados do relatório
                        dados_relatorio.append({
                            'cpf': cpf,
                            'nome_completo': nome_completo,
                            'setor': setor,
                            'email': email,
                            'status': status,
                            'date_hour': date_hour,
                        })

    # Renderize o template com os dados do relatório
    return render(request, 'apps/ti/planilha_emails.html', {'dados_relatorio': dados_relatorio})

    

def relatorio_chips(request):
    # Inicialize listas vazias para armazenar os dados que serão exibidos na tabela
    dados_relatorio = []

    # Recupere todos os objetos NumbEmail do banco de dados
    num_emails = NumbEmail.objects.all()
    if request.method == 'GET':
        data_inicio = request.GET.get('data_inicio')
        data_fim = request.GET.get('data_fim')

        if data_inicio and data_fim:
            # Converta as datas de string para objetos datetime
            data_inicio = datetime.strptime(data_inicio, '%Y-%m-%d')
            data_fim = datetime.strptime(data_fim, '%Y-%m-%d')

            num_emails = NumbEmail.objects.filter(data__range=(data_inicio, data_fim))

            # Itere sobre os objetos NumbEmail para processar os dados
            for num_email in num_emails:
                # Inicialize as variáveis gerais como vazias
                cpf = ""
                nome_completo = ""
                setor = ""
                operadora_site = ""
                numero = ""
                status = ""
                date_hour = ""

                # Verifique se há um número de telefone associado (não vazio)
                if num_email.numero:
                    # Recupere o funcionário associado ao CPF do objeto NumbEmail
                    try:
                        funcionario = Funcionario.objects.get(cpf=num_email.cpf)
                    except Funcionario.DoesNotExist:
                        funcionario = None

                    # Verifique se o funcionário foi encontrado e está ativo
                    if funcionario and funcionario.status_atividade == 'ativo':
                        # Preencha as variáveis com os dados do funcionário e do objeto NumbEmail
                        cpf = num_email.cpf
                        nome_completo = funcionario.nome_completo
                        setor = funcionario.setor
                        operadora_site = num_email.operadora_site
                        ddd = num_email.ddd
                        numero = num_email.numero
                        status = num_email.status_numb
                        date_hour = num_email.data

                        # Adicione os dados à lista de dados do relatório
                        dados_relatorio.append({
                            'cpf': cpf,
                            'nome_completo': nome_completo,
                            'setor': setor,
                            'operadora_site': operadora_site,
                            'ddd':ddd,
                            'numero': numero,
                            'status': status,
                            'date_hour': date_hour
                        })

    # Renderize o template com os dados do relatório
    return render(request, 'apps/ti/relatorio_chips.html', {'dados_relatorio': dados_relatorio})

def form_addti(request):
    funcionarios = Funcionario.objects.all()
    if request.method == 'POST':
        if 'funcionario' in request.POST:
            cpf_funcionario = request.POST.get('funcionario')
            funcionario = Funcionario.objects.get(cpf=cpf_funcionario)
            operadora_site = ""
            ddd = ""
            numero = ""
            email = ""
            senha_email = ""
            numero_existe = False
            email_existe = False
            sucesso = False
            success_message = f"{numero} salvo no cadastro de {funcionario.nome_completo}"
            if 'numero' in request.POST and request.POST['numero']:
                if 'operadora_site' in request.POST and 'ddd' in request.POST:
                    operadora_site = request.POST['operadora_site']
                    ddd = request.POST['ddd']
                    numero = request.POST['numero']
                    numero_existe = True
                    sucesso = True
                else:
                    error_message = "Por favor, preencha os campos Operadora/Site e DDD antes de salvar."

templates/apps/ti/form_addti.html
<!-- form_addti.html -->

{% extends "base.html" %}
{% load static %}
{% block addstyle_extra %}
<link rel="stylesheet" href="{% static "css/style_form.css" %}">
{% endblock  %}
{% block content %}
<section class="container-main">
    <!-- Formulário 1: Selecionar Funcionário -->
    <form action="{% url 'form_addti' %}" method="POST">
        {% csrf_token %}
        <label for="id_funcionario">Selecione o Funcionário:</label>
        <select id="id_funcionario" name="funcionario">
            {% for funcionario in funcionarios %}
                <option value="{{ funcionario.cpf }}">{{ funcionario.nome_completo }} - {{ funcionario.cpf }} - {{ funcionario.setor }}</option>
            {% endfor %}
        </select> <!-- Adicionei a tag de fechamento para o seletor de funcionário -->

        <!-- Restante do formulário de informações de contato -->
        <label for="id_operadora_site">Operadora/Site:</label>
        <input type="text" id="id_operadora_site" name="operadora_site">
        
        <label for="id_ddd">DDD:</label>
        <input type="text" id="id_ddd" name="ddd">
        
        <label for="id_numero">Número (com 9 e sem outros caracteres e espaço):</label>
        <input type="text" id="id_numero" name="numero">

        <label for="id_email">Email (comercial/da empresa):</label>
        <input type="text" id="id_email" name="email">
        
        <label for="id_senha_email">Senha:</label>
        <input type="text" id="id_senha_email" name="senha_email">
        
        <button type="submit">Salvar</button>
    </form>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
</section>

{% endblock %}

templates/apps/ti/planilha_emails.html
{% extends "base.html" %}
{% load static %}

{% block addstyle_extra %}
<link rel="stylesheet" href="{% static "css/style_subform.css" %}">
{% endblock  %}

{% block content %}
<section class="container-main">
    <form method="GET" class="dataFilter">
        <label for="data_inicio">Data Início:</label>
        <input type="date" id="data_inicio" name="data_inicio">
        <label for="data_fim">Data Fim:</label>
        <input type="date" id="data_fim" name="data_fim">
        <button type="submit">Filtrar</button>
    </form>

    <table class="table">
        <thead>
            <tr>
                <th>Nome Completo</th>
                <th>CPF</th>
                <th>Setor</th>
                <th>E-mails</th>
                <th>Status</th>
                <th>Modificação</th>
            </tr>
        </thead>
        <tbody>
            {% for dados in dados_relatorio %}
            <tr>
                <td>{{ dados.nome_completo }}</td>
                <td>{{ dados.cpf }}</td>
                <td>{{ dados.setor }}</td>
                <td>{{ dados.email }}</td>
                <td>{{ dados.status }}</td>
                <td>
                    {% if dados.status == 'ativo' %}
                        <a href="{% url 'inativar_email' dados.email dados.date_hour %}"><i class="fas fa-toggle-off"></i></a>
                        <a href="{% url 'excluir_email' dados.email dados.date_hour %}"><i class="fas fa-trash-alt"></i></a>
                    {% else %}
                        <a href="{% url 'excluir_email' dados.email dados.date_hour %}"><i class="fas fa-trash-alt"></i></a>
                    {% endif %}
                    
                </td>
            </tr>
            {% endfor %}
        </tbody>        
    </table>
</section>
{% endblock %}

templates/apps/ti/relatorio_chips.html
{% extends "base.html" %}
{% load static %}

{% block addstyle_extra %}
<link rel="stylesheet" href="{% static "css/style_subform.css" %}">
{% endblock  %}

{% block content %}
<section class="container-main">
    <form method="GET" class="dataFilter">
        <label for="data_inicio">Data Início:</label>
        <input type="date" id="data_inicio" name="data_inicio">
        <label for="data_fim">Data Fim:</label>
        <input type="date" id="data_fim" name="data_fim">
        <button type="submit">Filtrar</button>
    </form>

    <table class="table">
        <thead>
            <tr>
                <th>Nome Completo</th>
                <th>CPF</th>
                <th>Setor</th>
                <th>Operadora/Site</th>
                <th>Número</th>
                <th>Status</th>
                <th>Modificação</th>
            </tr>
        </thead>
        <tbody>
            {% for dados in dados_relatorio %}
            <tr>
                <td>{{ dados.nome_completo }}</td>
                <td>{{ dados.cpf }}</td>
                <td>{{ dados.setor }}</td>
                <td>{{ dados.operadora_site }}</td>
                <td>{{ dados.ddd }} - {{ dados.numero }}</td>
                <td>{{ dados.status }}</td>
                <td>
                    {% if dados.status == 'ativo' %}
                        <a href="{% url 'banir_numero' dados.numero dados.date_hour %}"><i class="fas fa-ban"></i></a>
                    {% endif %}
                    {% if dados.status == 'ativo' %}
                        <a href="{% url 'reciclar_numero' dados.numero dados.date_hour %}"><i class="fas fa-recycle"></i></a>
                    {% endif %}    
                    {% if dados.status == 'reciclar' %}
                        <a href="{% url 'reciclado_numero' dados.numero dados.date_hour %}"><i class="fas fa-recycle"></i></a>
                    {% endif %}
                    <a href="{% url 'excluir_numb' dados.numero dados.date_hour %}"><i class="fas fa-trash-alt"></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</section>
{% endblock %}