financeiro/urls.py
from django.urls import path
from .views import form_gastos, relat_geral, relat_setor

urlpatterns = [
    path('form_gastos/', form_gastos, name="form_gastos"),
    path('relat_geral/', relat_geral, name="relat_geral"),
    path('relat_setor/', relat_setor, name="relat_setor"),
]

rh/urls.py
from django.urls import path
from .views import list_funcionarios, list_salarios, list_beneficios, form_funcionarios

urlpatterns = [
    path('funcionarios/', list_funcionarios, name="list_funcionarios"),
    path('salarios/', list_salarios, name="list_salarios"),
    path('beneficios/', list_beneficios, name="list_beneficios"),
    path('cadastrar_funcionario/', form_funcionarios, name="form_funcionarios"),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('rh.urls')),
    path('', include('ti.urls')),
    path('', include('financeiro.urls')),
]

financeiro/models.py
from django.db import models
from rh.models import Funcionario
from datetime import datetime

class Conta(models.Model):
    nome = models.CharField(max_length=20)
    vencimento_dia = models.IntegerField()
    TIPOS_CHOICES = [
        ('GERAL', 'Geral'),
        ('SISTEMA', 'Sistema'),
        ('VOIP', 'Voip'),
    ]
    tipo_conta = models.CharField(max_length=20, choices=TIPOS_CHOICES)

    # SETORES
    Atendimento_POA = models.BooleanField(default=False)
    Atendimento_SM = models.BooleanField(default=False)
    Atendimento_SLE = models.BooleanField(default=False)
    SIAPE = models.BooleanField(default=False)
    INSS = models.BooleanField(default=False)
    TI = models.BooleanField(default=False)
    Marketing = models.BooleanField(default=False)
    Operacional = models.BooleanField(default=False)
    Outros = models.BooleanField(default=False)

    # EMPRESAS
    BOREAL = models.BooleanField(default=False)
    MONEY = models.BooleanField(default=False)
    PARK_GUAIBA = models.BooleanField(default=False)

    # Registro automativo de DATA:HORA
    data_cadastro = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nome

class Gasto(models.Model):
    def comprovante_upload_path(instance, filename):
        now = datetime.now()
        return f'comprovantes/{now.year}{now.month}/{filename}'

    nome_associado = models.CharField(max_length=100)
    valor_pago = models.DecimalField(max_digits=10, decimal_places=2)
    STATUS_CHOICES = [
        ('Pago', 'Pago'),
        ('A pagar', 'A pagar'),
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="A pagar")
    comprovante = models.FileField(upload_to=comprovante_upload_path, null=True, blank=True)

    # Registro automativo de DATA:HORA
    data_cadastro = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nome

financeiro/forms.py
from django import forms
from .models import Conta, Gasto

class ContaForm(forms.ModelForm):
    class Meta:
        model = Conta
        fields = '__all__'

class GastoForm(forms.ModelForm):
    class Meta:
        model = Gasto
        fields = '__all__'

financeiro/views.py
from django.shortcuts import render, redirect
from .forms import ContaForm, GastoForm
from .models import Conta, Gasto

def form_gastos(request):
    conta_form = ContaForm()
    gasto_form = GastoForm()

    if request.method == 'POST':
        if 'nome' in request.POST:  # Verifica se o formulário de Conta foi submetido
            conta_form = ContaForm(request.POST)
            if conta_form.is_valid():
                conta_form.save()
                # Lógica de redirecionamento ou outras ações após o salvamento da conta
                return redirect('form_gastos')
        elif 'nome_associado' in request.POST:  # Verifica se o formulário de Gasto foi submetido
            gasto_form = GastoForm(request.POST, request.FILES)
            if gasto_form.is_valid():
                gasto_form.save()
                # Lógica de redirecionamento ou outras ações após o salvamento do gasto
                return redirect('form_gastos')
    
    # Obtém todas as contas do banco de dados
    contas = Conta.objects.all()

    context = {
        'conta_form': conta_form,
        'gasto_form': gasto_form,
        'contas': contas,  # Envia as contas para o template
    }
    return render(request, 'apps/financeiro/forms_gastosContas.html', context)



def relat_geral(request):
    pass

def relat_setor(request):
    pass

templates/apps/financeiro/forms_gastosContas.html
{% extends "base.html" %}
{% load static %}
{% block addstyle_extra %}
<link rel="stylesheet" href="{% static "css/style_form.css" %}">
{% endblock  %}
{% block content %}
<section class="container-main">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2>Formulário de Conta</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <h4>Informações Gerais</h4>
                        <span class="box-form width100">
                            <label for="id_nome">Nome da Conta:</label>
                            <input type="text" name="nome" id="id_nome" required>
                        </span>
                        <span class="box-form width100">
                            <label for="id_vencimento_dia">Dia de Vencimento:</label>
                            <input type="number" name="vencimento_dia" id="id_vencimento_dia" required>
                        </span>
                        <span class="box-form width100">
                            <label for="id_tipo_conta">Tipo de Conta:</label>
                            <select name="tipo_conta" id="id_tipo_conta" required>
                                <option value="GERAL">Geral</option>
                                <option value="SISTEMA">Sistema</option>
                                <option value="VOIP">Voip</option>
                            </select>
                        </span>
                    </div>
                    
                    <div class="form-group">
                        <h4>Setores</h4>
                        <div class="setor-form">
                            <span class="box-form">
                                <label for="id_Atendimento_POA">Atendimento POA:</label>
                                <input type="checkbox" name="Atendimento_POA" id="id_Atendimento_POA">
                            </span>
                            <span class="box-form">
                                <label for="id_Atendimento_SM">Atendimento SM:</label>
                                <input type="checkbox" name="Atendimento_SM" id="id_Atendimento_SM">
                            </span>
                            <span class="box-form">
                                <label for="id_Atendimento_SLE">Atendimento SLE:</label>
                                <input type="checkbox" name="Atendimento_SLE" id="id_Atendimento_SLE">
                            </span>
                        </div>
                        <div class="setor-form">
                            <span class="box-form">
                                <label for="id_SIAPE">SIAPE:</label>
                                <input type="checkbox" name="SIAPE" id="id_SIAPE">
                            </span>
                            <span class="box-form">
                                <label for="id_INSS">INSS:</label>
                                <input type="checkbox" name="INSS" id="id_INSS">
                            </span>
                            <span class="box-form">
                                <label for="id_TI">TI:</label>
                                <input type="checkbox" name="TI" id="id_TI">
                            </span>
                        </div>
                        <div class="setor-form">
                            <span class="box-form">
                                <label for="id_Marketing">Marketing:</label>
                                <input type="checkbox" name="Marketing" id="id_Marketing">
                            </span>
                            <span class="box-form">
                                <label for="id_Operacional">Operacional:</label>
                                <input type="checkbox" name="Operacional" id="id_Operacional">
                            </span>
                            <span class="box-form">
                                <label for="id_Outros">Outros:</label>
                                <input type="checkbox" name="Outros" id="id_Outros">
                            </span>
                        </div>

                    </div>
                    
                    <div class="form-group">
                        <h4>Empresas</h4>
                        <div class="setor-form">
                            <span class="box-form">
                                <label for="id_BOREAL">Boreal:</label>
                                <input type="checkbox" name="BOREAL" id="id_BOREAL">
                            </span>
                            <span class="box-form">
                                <label for="id_MONEY">Money:</label>
                                <input type="checkbox" name="MONEY" id="id_MONEY">
                            </span>
                            <span class="box-form">
                                <label for="id_PARK_GUAIBA">Park Guaiba:</label>
                                <input type="checkbox" name="PARK_GUAIBA" id="id_PARK_GUAIBA">
                            </span>
                        </div>

                    </div>         
                    <span class="box-button">
                        <button type="submit" class="btn btn-primary">Salvar</button>
                    </span>  
                </form>
            </div>
            <div class="col-md-6">
                <h2>Formulário de Gasto</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <h4>Informações Gerais</h4>
                        <span class="box-form width100">
                            <label for="id_nome_associado">Nome Associado:</label>
                            <select name="nome_associado" id="id_nome_associado" required>
                                {% for conta in contas %}
                                    <option value="{{ conta.nome }}">{{ conta.nome }}</option>
                                {% endfor %}
                            </select>
                        </span>
                        <span class="box-form width100">
                            <label for="id_valor_pago">Valor Pago:</label>
                            <input type="text" name="valor_pago" id="id_valor_pago" required pattern="[0-9]+(\.[0-9]{2})?" title="Use o formato 000.00">
                        </span>
                        <span class="box-form">
                            <label for="id_status">Status:</label>
                            <input type="checkbox" name="status" id="id_status" value="Pago"> Pago
                        </span>
                    </div>
                    <div class="form-group">
                        <h4>Comprovante</h4>
                        <span class="box-form">
                            <label for="id_comprovante">Comprovante:</label>
                            <input type="file" name="comprovante" id="id_comprovante" accept=".pdf" required>
                        </span>
                    </div>
                    
                    <span class="box-button">
                        <button type="submit" class="btn btn-primary">Salvar</button>
                    </span> 
                </form>
            </div>
            
        </div>
    </div>
</section>
{% endblock %}